Insert into "CreativeTemplate" (CREATIVETEMPLATEID,NAME,TEMPLATE,STATUS) values (10,'zGIF/JPG','GIF','A');
Insert into "CreativeTemplate" (CREATIVETEMPLATEID,NAME,TEMPLATE,STATUS) values (11,'RM: HTML w/ Wrapper','Generic','A');
Insert into "CreativeTemplate" (CREATIVETEMPLATEID,NAME,TEMPLATE,STATUS) values (12,'zThird Party GIF/JPG','ThirdPartyGIF','A');
Insert into "CreativeTemplate" (CREATIVETEMPLATEID,NAME,TEMPLATE,STATUS) values (13,'PC Premier/Sponsor Link','SponsorLink','A');
Insert into "CreativeTemplate" (CREATIVETEMPLATEID,NAME,TEMPLATE,STATUS) values (14,'zHorz Text Box','HorzTextBox','A');
Insert into "CreativeTemplate" (CREATIVETEMPLATEID,NAME,TEMPLATE,STATUS) values (15,'zVert Text Box','VertTextBox','A');
Insert into "CreativeTemplate" (CREATIVETEMPLATEID,NAME,TEMPLATE,STATUS) values (16,'zInfo Button Bar','InfoButtonBar','A');
Insert into "CreativeTemplate" (CREATIVETEMPLATEID,NAME,TEMPLATE,STATUS) values (17,'zInfo Text Bar','InfoTextBar','A');
Insert into "CreativeTemplate" (CREATIVETEMPLATEID,NAME,TEMPLATE,STATUS) values (18,'RM: HTML','HTML','A');
Insert into "CreativeTemplate" (CREATIVETEMPLATEID,NAME,TEMPLATE,STATUS) values (19,'GIF/JPG','GIFHeader','A');
Insert into "CreativeTemplate" (CREATIVETEMPLATEID,NAME,TEMPLATE,STATUS) values (20,'Third Party GIF/JPG','ThirdPartyGIFHeader','A');
Insert into "CreativeTemplate" (CREATIVETEMPLATEID,NAME,TEMPLATE,STATUS) values (21,'zFPP','TabbedInfoblock','A');
Insert into "CreativeTemplate" (CREATIVETEMPLATEID,NAME,TEMPLATE,STATUS) values (22,'Circular','Circular','A');
Insert into "CreativeTemplate" (CREATIVETEMPLATEID,NAME,TEMPLATE,STATUS) values (23,'zDeal of the Week','DOTW','A');
Insert into "CreativeTemplate" (CREATIVETEMPLATEID,NAME,TEMPLATE,STATUS) values (24,'Third Party Iframe','ThirdPartyRichMedia','A');
Insert into "CreativeTemplate" (CREATIVETEMPLATEID,NAME,TEMPLATE,STATUS) values (25,'Programmable Creative','ProgrammableCreative','A');
Insert into "CreativeTemplate" (CREATIVETEMPLATEID,NAME,TEMPLATE,STATUS) values (26,'zSpecial Offer Text Links','SOTL','A');
Insert into "CreativeTemplate" (CREATIVETEMPLATEID,NAME,TEMPLATE,STATUS) values (27,'Launchpad Links','LaunchpadLinks','A');
Insert into "CreativeTemplate" (CREATIVETEMPLATEID,NAME,TEMPLATE,STATUS) values (28,'zPower Box Link','PowerBoxLink','A');
Insert into "CreativeTemplate" (CREATIVETEMPLATEID,NAME,TEMPLATE,STATUS) values (29,'zDLX Infoboard Premiere','DLXInfoboard','A');
Insert into "CreativeTemplate" (CREATIVETEMPLATEID,NAME,TEMPLATE,STATUS) values (30,'zInfo Button','InfoButton','A');
Insert into "CreativeTemplate" (CREATIVETEMPLATEID,NAME,TEMPLATE,STATUS) values (31,'Shared Resource Center','SharedResourceCenter','A');
Insert into "CreativeTemplate" (CREATIVETEMPLATEID,NAME,TEMPLATE,STATUS) values (32,'zExclusive Resource Center','ExclusiveResourceCenter','A');
Insert into "CreativeTemplate" (CREATIVETEMPLATEID,NAME,TEMPLATE,STATUS) values (33,'zPower Tool Link','PowerToolLink','A');
Insert into "CreativeTemplate" (CREATIVETEMPLATEID,NAME,TEMPLATE,STATUS) values (34,'zPower Feature Link','PowerFeatureLink','A');
Insert into "CreativeTemplate" (CREATIVETEMPLATEID,NAME,TEMPLATE,STATUS) values (35,'zPower Feature Logo','PowerFeatureLogo','A');
Insert into "CreativeTemplate" (CREATIVETEMPLATEID,NAME,TEMPLATE,STATUS) values (36,'zInfoblock with Tabs','InfoblockTab','A');
Insert into "CreativeTemplate" (CREATIVETEMPLATEID,NAME,TEMPLATE,STATUS) values (37,'Category Promo Line','CatPromoLine','A');
Insert into "CreativeTemplate" (CREATIVETEMPLATEID,NAME,TEMPLATE,STATUS) values (38,'Category Spotlight','CatSpot','A');
Insert into "CreativeTemplate" (CREATIVETEMPLATEID,NAME,TEMPLATE,STATUS) values (39,'Hard Code','HardCode','A');
Insert into "CreativeTemplate" (CREATIVETEMPLATEID,NAME,TEMPLATE,STATUS) values (40,'Sponsored Text Link','SponsoredTextLink','A');
Insert into "CreativeTemplate" (CREATIVETEMPLATEID,NAME,TEMPLATE,STATUS) values (41,'Vendor Content','VendorContent','A');
Insert into "CreativeTemplate" (CREATIVETEMPLATEID,NAME,TEMPLATE,STATUS) values (42,'Text Link','TextLink','A');
Insert into "CreativeTemplate" (CREATIVETEMPLATEID,NAME,TEMPLATE,STATUS) values (43,'Flash - Single File','Flash','A');
Insert into "CreativeTemplate" (CREATIVETEMPLATEID,NAME,TEMPLATE,STATUS) values (44,'zThink Tank Upper','ThinkTankUpper','I');
Insert into "CreativeTemplate" (CREATIVETEMPLATEID,NAME,TEMPLATE,STATUS) values (45,'zThink Tank Lower','ThinkTankLower','I');
Insert into "CreativeTemplate" (CREATIVETEMPLATEID,NAME,TEMPLATE,STATUS) values (46,'Info Button Premier','InfoButtonPremier','A');
Insert into "CreativeTemplate" (CREATIVETEMPLATEID,NAME,TEMPLATE,STATUS) values (47,'Site Skin','SiteSkin','A');
Insert into "CreativeTemplate" (CREATIVETEMPLATEID,NAME,TEMPLATE,STATUS) values (48,'zSolution Showcase','SolutionShowcase','A');
Insert into "CreativeTemplate" (CREATIVETEMPLATEID,NAME,TEMPLATE,STATUS) values (49,'GIF/JPG for RSS','RSS','A');
Insert into "CreativeTemplate" (CREATIVETEMPLATEID,NAME,TEMPLATE,STATUS) values (50,'zExclusive Resource Center (Branded)','ExclusiveResourceCenterBranded','A');
Insert into "CreativeTemplate" (CREATIVETEMPLATEID,NAME,TEMPLATE,STATUS) values (51,'Cross Promotional Line','CrossPromoLine','A');
Insert into "CreativeTemplate" (CREATIVETEMPLATEID,NAME,TEMPLATE,STATUS) values (52,'RM: Javascript','Javascript','A');
Insert into "CreativeTemplate" (CREATIVETEMPLATEID,NAME,TEMPLATE,STATUS) values (53,'Power Center','PowerCenterSubcreative','A');
Insert into "CreativeTemplate" (CREATIVETEMPLATEID,NAME,TEMPLATE,STATUS) values (54,'RM: XML Broadband','Broadband','A');
Insert into "CreativeTemplate" (CREATIVETEMPLATEID,NAME,TEMPLATE,STATUS) values (55,'zFeature Program and Collection','FeatureProgramCollection','A');
Insert into "CreativeTemplate" (CREATIVETEMPLATEID,NAME,TEMPLATE,STATUS) values (56,'RM: XML GIF/JPG/SWF','XmlJPG','A');
Insert into "CreativeTemplate" (CREATIVETEMPLATEID,NAME,TEMPLATE,STATUS) values (57,'Vendor Asset','VendorAsset','A');
Insert into "CreativeTemplate" (CREATIVETEMPLATEID,NAME,TEMPLATE,STATUS) values (58,'zXML Trinity','BVideoMulti','A');
Insert into "CreativeTemplate" (CREATIVETEMPLATEID,NAME,TEMPLATE,STATUS) values (59,'Logo Box','LogoBox','A');
Insert into "CreativeTemplate" (CREATIVETEMPLATEID,NAME,TEMPLATE,STATUS) values (60,'Vendor Text Links','VendorTextLink','A');
Insert into "CreativeTemplate" (CREATIVETEMPLATEID,NAME,TEMPLATE,STATUS) values (61,'Info Board','InfoBoard','A');
Insert into "CreativeTemplate" (CREATIVETEMPLATEID,NAME,TEMPLATE,STATUS) values (63,'Product Showcase','ProductShowcase','A');
Insert into "CreativeTemplate" (CREATIVETEMPLATEID,NAME,TEMPLATE,STATUS) values (64,'zYahoo Flash - Single File','FlashYahoo','A');
Insert into "CreativeTemplate" (CREATIVETEMPLATEID,NAME,TEMPLATE,STATUS) values (65,'zYahoo Third Party GIF/JPG','ThirdPartyGIFHeaderYahoo','A');
Insert into "CreativeTemplate" (CREATIVETEMPLATEID,NAME,TEMPLATE,STATUS) values (66,'zYahoo Javascript','JavascriptYahoo','A');
Insert into "CreativeTemplate" (CREATIVETEMPLATEID,NAME,TEMPLATE,STATUS) values (67,'zRM: Yahoo HTML','HTMLYahoo','A');
Insert into "CreativeTemplate" (CREATIVETEMPLATEID,NAME,TEMPLATE,STATUS) values (68,'zYahoo GIF/JPG','GIFHeaderYahoo','A');
Insert into "CreativeTemplate" (CREATIVETEMPLATEID,NAME,TEMPLATE,STATUS) values (69,'zYahoo Third Party Iframe','ThirdPartyRichMediaYahoo','A');
Insert into "CreativeTemplate" (CREATIVETEMPLATEID,NAME,TEMPLATE,STATUS) values (70,'zRM: Yahoo HTML w/ Wrapper','GenericYahoo','A');
Insert into "CreativeTemplate" (CREATIVETEMPLATEID,NAME,TEMPLATE,STATUS) values (71,'Vendor Spotlight','VendorSpotlight','A');
Insert into "CreativeTemplate" (CREATIVETEMPLATEID,NAME,TEMPLATE,STATUS) values (72,'Product Highlight','ProductHighlight','A');
Insert into "CreativeTemplate" (CREATIVETEMPLATEID,NAME,TEMPLATE,STATUS) values (73,'RM: Video Podcast','VideoPodcast','A');
Insert into "CreativeTemplate" (CREATIVETEMPLATEID,NAME,TEMPLATE,STATUS) values (74,'Exclusive Resource Center Plus','ExclusiveResourceCenterPlus','A');
Insert into "CreativeTemplate" (CREATIVETEMPLATEID,NAME,TEMPLATE,STATUS) values (77,'RM: Sports Active Header','SportsActiveHeader','A');
Insert into "CreativeTemplate" (CREATIVETEMPLATEID,NAME,TEMPLATE,STATUS) values (75,'RM: Break in the Action','BreakInAction','A');
Insert into "CreativeTemplate" (CREATIVETEMPLATEID,NAME,TEMPLATE,STATUS) values (78,'Sports Marketing E-mail Sign-up','SportsEmailSignup','A');
Insert into "CreativeTemplate" (CREATIVETEMPLATEID,NAME,TEMPLATE,STATUS) values (79,'zSports Site Skin','SportsSiteSkin','A');
Insert into "CreativeTemplate" (CREATIVETEMPLATEID,NAME,TEMPLATE,STATUS) values (80,'Over Text','OverText','A');
Insert into "CreativeTemplate" (CREATIVETEMPLATEID,NAME,TEMPLATE,STATUS) values (81,'RM: XMFB','XMFB','A');
Insert into "CreativeTemplate" (CREATIVETEMPLATEID,NAME,TEMPLATE,STATUS) values (82,'Blank Creative','Blank','A');
Insert into "CreativeTemplate" (CREATIVETEMPLATEID,NAME,TEMPLATE,STATUS) values (83,'HotSpot','HotSpot','A');
Insert into "CreativeTemplate" (CREATIVETEMPLATEID,NAME,TEMPLATE,STATUS) values (84,'Sports Marketing Box','SportsMarketingBox','A');
Insert into "CreativeTemplate" (CREATIVETEMPLATEID,NAME,TEMPLATE,STATUS) values (85,'Sports Sky One','SportsSkyOne','A');
Insert into "CreativeTemplate" (CREATIVETEMPLATEID,NAME,TEMPLATE,STATUS) values (86,'zDeal Spotlight','DealSpotlight','A');
Insert into "CreativeTemplate" (CREATIVETEMPLATEID,NAME,TEMPLATE,STATUS) values (87,'Sports Text Links','SportsArenaOvers','A');
Insert into "CreativeTemplate" (CREATIVETEMPLATEID,NAME,TEMPLATE,STATUS) values (88,'Sponsored Feed','SponsoredFeed','A');
Insert into "CreativeTemplate" (CREATIVETEMPLATEID,NAME,TEMPLATE,STATUS) values (89,'RM: Pushdown','Pushdown','A');
Insert into "CreativeTemplate" (CREATIVETEMPLATEID,NAME,TEMPLATE,STATUS) values (90,'Dynamic Showcase','DynamicShowcase','A');
Insert into "CreativeTemplate" (CREATIVETEMPLATEID,NAME,TEMPLATE,STATUS) values (91,'Dynamic Sponsored Text Link','DynamicSponsoredTextLink','A');
Insert into "CreativeTemplate" (CREATIVETEMPLATEID,NAME,TEMPLATE,STATUS) values (92,'Hint','Hint','A');
Insert into "CreativeTemplate" (CREATIVETEMPLATEID,NAME,TEMPLATE,STATUS) values (93,'RM: Expand','Expand','A');
Insert into "CreativeTemplate" (CREATIVETEMPLATEID,NAME,TEMPLATE,STATUS) values (94,'zAC Awesome','ThirdPartyAC','A');
