Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (1,'Window','Window',90,120,'A','WINDOW',datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (2,'Banner','Banner',60,468,'A',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (3,'Leaderboard 728x90','Leaderboard',90,728,'A',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (4,'Button','Button',31,88,'A',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (5,'zMPU336','MPU336',280,336,'I','MPU',datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (6,'zHorz Text Box','Horizontal Text Box',0,0,'A',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (7,'zVert Text Box','Vertical Text Box',0,0,'A',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (8,'Sponsored Text Link','Sponsored Text Link',0,0,'A',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (9,'zInfo button Bar','CONTAINER Info Buttons',0,0,'I',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (10,'zInfo Text Bar','Info Text Bar',0,0,'A',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (31,'Skyscraper120x600','Skyscraper120x600',600,120,'A',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (12,'Skyscraper600','Skyscraper600',600,160,'A',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (13,'zVMU','Vertical Messaging Plus Unit',280,336,'I','VMU',datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (14,'zTLU','The Launch Unit',35,346,'I','TLU',datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (15,'zE Board','Explore Board',356,156,'I',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (16,'zBrick','multiple text links',0,0,'I',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (17,'Circular','Circular',220,485,'A','CIRCULAR',datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (18,'zILU','Impact Launch Unit',728,90,'I','LEADER',datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (34,'zInfo button Bar ZIP','Info Button Bar with zip code lookup',0,0,'I',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (20,'Infoblock','Infoblock',0,0,'I',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (21,'zInfoboard','Infoboard',728,90,'I','LEADER',datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (22,'zLogo','Logo',0,0,'I',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (23,'Logo Box','Logo Box',0,0,'A',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (35,'PC Premier Text Link','PC Premier Text Link',0,0,'A',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (36,'zSpecial Offers Text Link','Special Offers Text Link',0,0,'A',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (26,'Plain Text','Plain Text',0,0,'A',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (27,'Pop Under','Pop Under',1,1,'I',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (37,'zBRU Instream','BRU Instream',0,0,'I',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (29,'zText Block','Text Block',0,0,'I',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (38,'zEnterprise Premier Box Link','Enterprise Premier Box Link',0,0,'I',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (32,'VFP','VFP',0,0,'I',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (33,'zDeal of the Week','Deal of the Week',0,0,'A',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (11,'zEnterprise Premier Bar','Enterprise Premier Bar',0,0,'I',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (43,'zDOD','Deal of the Day',0,0,'I',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (40,'Launchpad Link','DL Launchpad Link',0,0,'A',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (41,'Featured Product','Featured Product',300,160,'I',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (42,'Marquee','Marquee',60,234,'A','MARQUEE',datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (44,'MPU300','MPU300',250,300,'A',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (45,'CONTAINER Power Tools','CONTAINER Power Tools',0,0,'I',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (46,'SuperStitial',' ',0,0,'I',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (47,'Intromercial','Prestitial',0,0,'A',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (48,'CONTAINER PC Premier & Special Offers','CONTAINER PC Premier & Special Offers',0,0,'A',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (49,'zArchway','Archway',340,728,'I','ARCHWAY',datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (50,'zCONTAINER Rotating Resource Box','CONTAINER Rotating Resource Box',250,300,'I',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (51,'zRotating Resource Box','Rotating Resource Box',250,300,'I',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (52,'CONTAINER Fixed Resource Box','CONTAINER Fixed Resource Box',250,300,'A',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (53,'zFixed Resource Box','Fixed Resource Box',250,300,'I',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (54,'CONTAINER Window Column','CONTAINER Window Column',0,0,'I',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (55,'zCONTAINER Solution Showcase','CONTAINER Solution Showcases',0,0,'A',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (56,'zSolution Showcase','Solution Showcase',125,350,'A',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (57,'Dynamic Showcase','Dynamic Showcase',0,0,'A',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (58,'zSuper Circular','Super Circular',0,0,'I',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (59,'CONTAINER Launchpad','CONTAINER Launchpad',0,0,'A',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (60,'Rectangle','Rectangle',150,180,'A',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (61,'Merchandise Display','Merchandise Display',0,0,'I',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (64,'CONTAINER Marquees','CONTAINER Marquees',0,0,'A',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (65,'zFlag','Flag',0,0,'I',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (66,'CONTAINER Power Box','CONTAINER Power Box',0,0,'A',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (67,'zPower Tool Link','Power Box Link',0,0,'A',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (68,'CONTAINER Info Buttons','CONTAINER Info Buttons',0,0,'A',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (69,'zBButton','BButton',0,0,'I',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (70,'zToolbar','Toolbar',0,0,'I',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (71,'zInfo Button','Info Button',0,0,'I',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (72,'CONTAINER Shared Resource Center','CONTAINER Shared Resource Center',0,0,'A',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (73,'Shared Resource Center','Shared Resource Center',0,0,'A',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (74,'Exclusive Resource Center','Exclusive Resource Center',0,0,'A',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (75,'CONTAINER Power Features','CONTAINER Power Features',0,0,'I',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (76,'zPower Feature Logo','Power Feature Logo',30,75,'A',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (77,'CONTAINER Window Block','CONTAINER Window Block',0,0,'A',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (78,'zPower Feature Link','Power Feature Link',0,0,'A',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (79,'Marquee300','Marquee300',60,300,'A','MARQUEE',datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (80,'Square Button','Square Button',125,125,'A',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (81,'CONTAINER Buttons','CONTAINER Buttons',0,0,'A',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (82,'Hard Code','Hard Code',0,0,'A',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (83,'Category Spotlight','Category Spotlight',0,0,'A',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (84,'zWidescreen','Widescreen',190,620,'I',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (85,'zMasthead','Masthead',59,520,'I',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (86,'zBigscreen','Bigscreen',160,458,'I',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (87,'Skin','Skin',0,0,'A',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (88,'CONTAINER Vendor Content','CONTAINER Vendor Content',0,0,'A','C_VENDORCONTENT',datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (89,'Vendor Content','Vendor Content',0,0,'A','VENDORCONTENT',datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (90,'Half Page','Half Page',600,300,'A',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (91,'zShowroom','Model Showcase',0,0,'A',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (92,'z758x140','758x140',140,758,'I',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (93,'Insignia','Insignia',75,280,'A',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (94,'zBWindow','BWindow',90,120,'I',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (95,'CONTAINER Rectangle','CONTAINER Rectangle',0,0,'A',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (96,'CONTAINER Blog','CONTAINER Blog',0,0,'A',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (97,'Blog Text Link','Text Link',0,0,'A',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (98,'Blog Button','Button',31,88,'A',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (99,'zCustom','Custom',600,300,'I',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (100,'zThink Tank Upper','Think Tank Upper',0,0,'A',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (101,'zThink Tank Lower','Think Tank Lower',0,0,'A',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (102,'zCONTAINER Think Tank Lower','CONTAINER Think Tank Lower',0,0,'A',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (103,'Custom Unit','Custom Unit',0,0,'A',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (104,'Hotspot','Hotspot',0,0,'A',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (105,'International Forwarding','for International Forwarding - can be any size',0,0,'A',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (106,'Info Button Premier','Info Button Premier',0,0,'A',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (107,'Skylight','Skylight',60,120,'A',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (108,'zBSkylight','BSkylight',0,0,'I',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (109,'zRSSText Link','RSSText Link',0,0,'I',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (110,'CONTAINER Square Buttons','CONTAINER Square Buttons',0,0,'A',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (111,'MPU100','MPU100',100,300,'A',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (112,'Custom Text Link','Custom Text Link',0,0,'A',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (113,'CONTAINER Messaging Plus','CONTAINER Messaging Plus',0,0,'I',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (114,'Bandana','Bandana',84,432,'I',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (115,'Interstitial600','Prestitial',400,600,'I',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (116,'zBMarquee','BMarquee',0,0,'A',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (117,'zFloater','Floater',0,0,'A',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (118,'zXLong Marquee','XLong Marquee',0,0,'A',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (119,'Billboard','Billboard',350,980,'A',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (120,'Cross Promotional Line','Cross Promotional Line',0,0,'I',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (121,'Dynamic Header','Dynamic Header',90,982,'I',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (122,'Backsplash','Backsplash',900,1200,'A','BACKSPLASH',datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (123,'CONTAINER Power Centers','CONTAINER Power Centers',0,0,'I',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (124,'Power Center','Power Center Subcreative',0,0,'I',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (125,'zXButton','XButton',0,0,'A',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (126,'zXCONTAINER XButton','zXCONTAINER XButton',0,0,'A',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (134,'zCMB302x170','CMB302x170',0,0,'A',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (127,'zThink Tank','Think Tank',0,0,'A','NULL',datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (128,'CONTAINER Think Tank','CONTAINER Think Tank',0,0,'A','NULL',datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (129,'zFeatured Program Collection','Feature Program and Collection',0,0,'A',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (130,'CONTAINER Featured Program Collection','CONTAINER Feature Program and Collection',0,0,'A',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (133,'CONTAINER MPU100s','CONTAINER MPU100s',0,0,'A',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (135,'zCMB432x120','CMB432x120',0,0,'A',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (136,'Vertical Banner','Vertical Banner',240,120,'I',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (137,'zBVideoMPUSkinXC','BVideoMPUSkinXC',0,0,'A',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (138,'Vendor Asset','Vendor Asset',0,0,'I',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (139,'CONTAINER Logo Box','CONTAINER Logo Box',0,0,'A',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (140,'Window176','Window176',90,176,'A',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (141,'zWindow176a','Window176',90,176,'I',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (142,'zWindow176b','Window176',90,176,'I',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (143,'Animated Gutter','Animated Gutter',1200,439,'I',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (144,'XVideoOverlay','XVideoOverlay',0,0,'I',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (145,'Vendor Text Link','Vendor Text Link',0,0,'A',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (146,'Info Board','Info Board',0,0,'A',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (147,'CPN300x550','CPN300x550',0,0,'A',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (148,'CPN160x800','CPN160x800',0,0,'A',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (149,'CPN500x360','CPN500x360',0,0,'A',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (150,'XVideo','XVideo',0,0,'A',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (151,'CPN300x450','CPN300x450',450,300,'A',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (152,'zBOverlay','BOverlay',0,0,'A',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (153,'XVideocast','XVideocast',0,0,'A',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (154,'MPU200','MPU200',200,300,'I',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (155,'Interstitial640','Interstitial640',480,640,'I',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (156,'XMPU100','XMPU100',100,300,'I',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (157,'BMPU100','BMPU100',100,300,'A',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (158,'Extended Sponsored Text Link','Extended Sponsored Text Link',0,0,'A',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (159,'Blank','Blank',0,0,'A',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (160,'zSuper Leader','zSuper Leader',150,880,'I',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (161,'Vendor Spotlight','Vendor Spotlight',0,0,'A',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (162,'Product Showcase','Product Showcase',0,0,'A',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (163,'Content Curl','Content Curl',0,0,'I',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (164,'zSliver','Sliver',0,0,'A',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (165,'CPN160x1200','CPN160x1200',0,0,'A',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (166,'CPN300x250','CPN300x250',0,0,'A',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (167,'zBOverlayButtonOld','BOverlayButton',0,0,'I',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (168,'zBOverlayButton','BOverlayButton',0,0,'A',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (169,'zBOverlayMPU100','BOverlayMPU100',0,0,'A',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (170,'CPN160x690','CPN160x690',0,0,'A',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (171,'Shoulderpad','Shoulderpad',90,184,'I',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (172,'Rectangle192x64','Rectangle192x64',64,192,'A',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (173,'Marquee300x40','Marquee300x40',40,300,'A',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (174,'zCONTAINER Product Highlight','CONTAINER Product Highlight',0,0,'I',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (175,'zProduct Highlight','Product Highlight',0,0,'I',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (176,'CONTAINER Marquee300','CONTAINER Marquee300',0,0,'A',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (177,'Product Highlight','Product Highlight',0,0,'A',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (178,'CONTAINER Product Highlight','CONTAINER Product Highlight',0,0,'A',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (179,'zMain Feature Block','Main Feature Block',300,981,'A',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (180,'zMantle Skin','Mantle Skin',1000,1285,'A',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (181,'Panel','Panel',300,728,'A',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (182,'CONTAINER Skylight','CONTAINER Skylight',0,0,'A',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (183,'630x90','630x90',90,630,'A',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (184,'CPN300x380','CPN300x380',0,0,'A',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (185,'Rectangle284x100','Rectangle284x100',100,284,'I',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (186,'Rectangle 248x77','Rectangle 248x77',77,248,'I',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (187,'Marquee 234x42','Marquee 234x42',42,234,'A',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (188,'Square 160x160','Square 160x160',160,160,'A',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (189,'Square 400x400','Square 400x400',400,400,'A',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (190,'1285x500','1285x500',500,1285,'I',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (191,'Button 150x20','Button 150x20',20,150,'I',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (192,'Button 130x40','Button 130x40',40,130,'I',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (193,'Rectangle 308x28','Rectangle 308x28',28,308,'I',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (194,'Rectangle 272x204','Rectangle 272x204',204,272,'I',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (195,'Rectangle 280x77','Rectangle 280x77',77,280,'A',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (196,'Banner 985x85','Banner 985x85',85,985,'I',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (197,'Banner 400x60','Banner 400x60',60,400,'I',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (198,'Banner 660x60','Banner 660x60',60,660,'A',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (199,'Banner 440x60','Banner 440x60',60,440,'I',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (200,'Button 130x160','Button 130x160',160,130,'I',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (201,'Button 90x80','Button 90x80',80,90,'I',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (202,'533x255','533x255',255,533,'I',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (203,'Rectangle 180x36','Rectangle 180x36',36,180,'I',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (204,'Button 80x20','Button 80x20',20,80,'A',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (205,'BBacksplash','BBacksplash',0,0,'A',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (206,'CPN160x507','CPN160x507',507,160,'A',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (207,'Pushdown 970x66','Pushdown 970x66',66,970,'A',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (208,'BMPU300','BMPU300',0,0,'A',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (209,'Tile','Tile',0,0,'A',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (210,'Text','Text',0,0,'A',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (211,'Over Text','Over Text',0,0,'A',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (212,'zXMFB','XMFB',300,981,'A',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (213,'Rectangle 185x210','Rectangle 185x210',0,0,'A',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (214,'Branded Canvas','Branded Canvas',0,0,'A',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (215,'XMarquee','XMarquee',60,234,'A',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (216,'Rectangle 300x28','Rectangle 300x28',28,300,'I',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (217,'CONTAINER Category Spotlight','CONTAINER Category Spotlight',0,0,'A',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (218,'Banner 960x250','Banner 960x250',250,960,'I',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (219,'Banner 980x150','Banner 980x150',150,980,'A',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (220,'XXL','XXL',648,468,'A',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (221,'Tower 336x700','Tower 336x700',700,336,'A',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (222,'MPU150','MPU150',150,300,'A',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (223,'Banner 980x45','Banner 980x45',45,980,'A',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (224,'Banner 780x45','Banner 780x45',45,780,'A',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (225,'Sponsored Feed','Sponsored Feed',115,625,'A',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (227,'zDeal Spotlight','Deal Spotlight',0,0,'I',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (228,'Custom Content Header','Custom Content Header',0,0,'A',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (229,'Sports Arena Overs','Sports Arena Overs',0,0,'A',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (230,'Product Listing','Product Listing',0,0,'A',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (231,'Button 79x45','Button 79x45',45,79,'A',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (232,'CONTAINER Dynamic Showcase','CONTAINER Dynamic Showcase',0,0,'A',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (233,'CONTAINER Sponsored Text Link','CONTAINER Sponsored Text Link',0,0,'A',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (234,'Dynamic Sponsored Text Link','Dynamic Sponsored Text Link',0,0,'A',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (235,'CONTAINER Dynamic Sponsored Text Link','CONTAINER Dynamic Sponsored Text Link',0,0,'A',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (236,'Hint','Hint',0,0,'A',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (237,'Banner 410x145','Banner 410x145',145,410,'A',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (238,'Banner 980x100','Banner 980x100',100,980,'A',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (239,'Banner 960x27','Banner 960x27',27,960,'A',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (240,'Banner 960x100','Banner 960x100',100,960,'A',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (241,'BButton VAST','BButton VAST',0,0,'I',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (242,'Billboard 970x250','Billboard 970x250',250,970,'A',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (243,'Banner 970x90','Banner 970x90',90,970,'A',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (244,'Banner 468x60','Banner 468x60',60,468,'A',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (245,'Magnet 468x60','Magnet 468x60',60,468,'A',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (246,'Slider 300x100','Slider 300x100',100,300,'A',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (247,'Portrait300x1050','Portrait300x1050',1050,300,'A',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (248,'Button 100x90','Button 100x90',90,100,'A',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (249,'Rectangle 580x260','Rectangle 580x260',260,580,'A',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (250,'Banner 620x90','Banner 620x90',90,620,'A',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (252,'Sports Presenting','Sports Presenting',90,970,'A',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (253,'Video','Video',0,0,'A',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (254,'Mobile','Mobile',0,0,'A',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (251,'Super Leader 970x66','Super Leader 970x66',66,970,'A',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (255,'Newsletter','Newsletter',0,0,'A',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (259,'Interactive Skin','Interactive Skin',0,0,'A',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (258,'new creative size','test',250,300,'I',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (257,'Slider 468x60','Slider 468x60',60,468,'A',null,datetime(),datetime());
Insert into "CreativeSize" (CREATIVESIZEID,NAME,DESCRIPTION,HEIGHT,WIDTH,STATUS,BUFFERNAME,INSERTDATE,UPDATEDATE) values (256,'Inline Product Carousel','Inline Product Carousel',0,0,'A','NULL',datetime(),datetime());
